connections:
poc_transformations_dbt:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: poc
      role_arn: "arn:aws:iam::481133585213:role/glue-dbt-role"
      region: us-east-2
      glue_version: "4.0"
      workers: 2
      worker_type: G.1X
      schema: "{{ var('target_glue_db', 'default') }}"
      session_provisioning_timeout_in_seconds: 240
      location: "{{ var('target_s3_bucket') }}"